version: 2
jobs:
  build:
    working_directory: ~/libri-client-js
    docker:
      - image: circleci/node:4
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ arch }}-{{ checksum "package.json" }}
      - run:
          name: npm install
          command: npm install
      - save_cache:
          key: dependency-cache-{{ arch }}-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: lint
          command: make lint
      - run:
          name: test
          command: make test acceptance
